[package]
name = "mz-secrets"
description = "Secrets Controller"
version = "0.0.0"
edition = "2021"
rust-version = "1.62.0"
publish = false

[dependencies]
anyhow = "1.0.60"
mz-repr = { path = "../repr" }
async-trait = "0.1.56"
